services:
  - type: web
    name: marrakech-dunes-backend
    env: node
    plan: starter
    region: frankfurt
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://hamzacharafeddine77:FxUfGGZ8VRyflrGW@marrakechtours-cluster.cvyntkb.mongodb.net/marrakech-tours
      - key: SESSION_SECRET
        value: FeU8jTYGmCars6u3qUX8uyMF5SkLxhkH9HrXv0rx162dcFGrf8TmfXEP27unxj0525rqj8w1uk
      - key: JWT_SECRET
        value: ct8B36w2JW68WY6ofFLarloQJxCXVQNcBofS0tM78767E69782944DABB
    disk:
      name: marrakech-assets
      mountPath: /app/attached_assets
      sizeGB: 1
    autoDeploy: true