services:
  - type: web
    name: marrakech-dunes-backend
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: <your-mongo-uri>
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_DEFAULT_PASSWORD
        sync: false
      - key: ADMIN_PHONE_AHMED
        sync: false
      - key: ADMIN_PHONE_YAHIA
        sync: false
      - key: ADMIN_PHONE_NADIA
        sync: false
    disk:
      name: marrakech-assets
      mountPath: /app/attached_assets
      sizeGB: 1
    autoDeploy: true
