import { Router, Request, Response } from "express";
import session from "express-session";

// Extend Request interface to include proper session typing
interface SessionRequest extends Request {
  session: session.Session & Partial<session.SessionData>;
}

const router = Router();

const respond = (_req: Request, res: Response) => res.sendStatus(204);

/**
 * GET /api/session/init
 * Initialize session and return CSRF token
 */
router.get("/init", (req: Request, res: Response) => {
  // CSRF token is already generated by generateCSRFToken middleware
  const csrfToken = res.locals.csrfToken || (req as any).csrfToken?.() || '';
  res.setHeader('X-Session-Init', 'new-handler');
  return res.status(200).json({ csrfToken, ok: true });
});

/**
 * POST /api/session/init
 * Initialize session (POST version)
 */
router.post("/init", respond);

router.get("/test", (req, res) => res.json({ ok: true }));

export default router;
