import { createHash } from 'node:crypto';
import dns from 'node:dns/promises';
import http from 'node:http';
import https from 'node:https';
import net from 'node:net';
import { GetObjectCommand, HeadObjectCommand, PutObjectCommand, type S3Client } from '@aws-sdk/client-s3';
import type { MigrationManifestEntry } from './object-storage-migration.js';

export const MAX_BYTES = 5 * 1024 * 1024;
const ALLOWED_TYPES = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/gif']);
export interface DownloadedSource { bytes: Buffer; contentType: string; sha256: string; }

function ipv4Number(value: string): number { return value.split('.').reduce((n, part) => (n * 256) + Number(part), 0) >>> 0; }
function ipv4Global(value: string): boolean {
  const n = ipv4Number(value); const ranges: Array<[number, number]> = [[0,0xff000000],[0x0a000000,0xff000000],[0x64400000,0xffc00000],[0x7f000000,0xff000000],[0xa9fe0000,0xffff0000],[0xac100000,0xfff00000],[0xc0000000,0xffffff00],[0xc0000200,0xffffff00],[0xc0a80000,0xffff0000],[0xc6120000,0xfffe0000],[0xc6336400,0xffffff00],[0xcb007100,0xffffff00],[0xe0000000,0xf0000000],[0xf0000000,0xf0000000]];
  return !ranges.some(([base, mask]) => ((n & mask) >>> 0) === (base >>> 0));
}
function ipv6Bytes(value: string): Uint8Array | undefined { let normalized = value.toLowerCase(); const lastColon = normalized.lastIndexOf(':'); const tail = normalized.slice(lastColon + 1); if (tail.includes('.')) { if (!net.isIPv4(tail)) return undefined; const n = ipv4Number(tail); normalized = `${normalized.slice(0, lastColon + 1)}${(n >>> 16).toString(16)}:${(n & 0xffff).toString(16)}`; } const pieces = normalized.split('::'); if (pieces.length > 2) return undefined; const left = pieces[0] ? pieces[0].split(':').filter(Boolean) : []; const right = pieces[1] ? pieces[1].split(':').filter(Boolean) : []; const groups = pieces.length === 2 ? [...left, ...Array(8 - left.length - right.length).fill('0'), ...right] : [...left, ...right]; if (groups.length !== 8) return undefined; const bytes = new Uint8Array(16); groups.forEach((group, i) => { const n = Number.parseInt(group, 16); if (!Number.isFinite(n) || n < 0 || n > 0xffff) throw new Error('invalid ipv6'); bytes[i * 2] = n >> 8; bytes[i * 2 + 1] = n & 255; }); return bytes; }
function ipv6Global(value: string): boolean { const bytes = ipv6Bytes(value); if (!bytes) return false; const mapped = bytes.slice(0, 10).every((v) => v === 0) && bytes[10] === 255 && bytes[11] === 255; if (mapped) return ipv4Global(`${bytes[12]}.${bytes[13]}.${bytes[14]}.${bytes[15]}`); if (bytes.every((v) => v === 0) || (bytes.slice(0, 15).every((v) => v === 0) && bytes[15] === 1)) return false; if ((bytes[0] & 0xfe) === 0xfc || (bytes[0] === 0xfe && (bytes[1] & 0xc0) === 0x80) || bytes[0] === 0xff) return false; if (bytes[0] === 0x20 && bytes[1] === 0x01 && bytes[2] === 0x0d && bytes[3] === 0xb8) return false; if (bytes[0] === 0xfe && (bytes[1] & 0xc0) === 0xc0) return false; if (bytes[0] === 0x00 && bytes[1] === 0x64 && bytes[2] === 0xff && bytes[3] === 0x9b && bytes.slice(4, 12).every((v) => v === 0)) return false; return true; }
function publicAddress(address: string): boolean { const normalized = address.replace(/^\[|\]$/g, ''); return net.isIPv4(normalized) ? ipv4Global(normalized) : net.isIPv6(normalized) ? ipv6Global(normalized) : false; }
async function resolvePinned(hostname: string): Promise<{ address: string; family: 4 | 6 }> { const normalized = hostname.replace(/^\[|\]$/g, ''); if (net.isIP(normalized)) { if (!publicAddress(normalized)) throw new Error('Migration source resolves to a non-public address'); return { address: normalized, family: net.isIPv4(normalized) ? 4 : 6 }; } const answers = await dns.lookup(normalized, { all: true }); if (!answers.length || answers.some(({ address }) => !publicAddress(address))) throw new Error('Migration source resolves to a non-public address'); const chosen = answers.slice().sort((a, b) => a.address.localeCompare(b.address))[0]; return { address: chosen.address, family: chosen.family as 4 | 6 }; }
function trustedPrefix(url: URL, prefixes: readonly string[]): boolean { return prefixes.some((prefix) => { try { const allowed = new URL(prefix); return !allowed.username && !allowed.password && !allowed.search && !allowed.hash && allowed.pathname.endsWith('/') && allowed.protocol === url.protocol && allowed.hostname.toLowerCase() === url.hostname.toLowerCase() && allowed.port === url.port && url.pathname.startsWith(allowed.pathname); } catch { return false; } }); }
function signatureMatches(type: string, bytes: Buffer): boolean { if (type === 'image/png') return bytes.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10])); if (type === 'image/jpeg') return bytes.subarray(0, 3).equals(Buffer.from([255,216,255])); if (type === 'image/gif') return ['GIF87a','GIF89a'].includes(bytes.subarray(0,6).toString('ascii')); return type === 'image/webp' && bytes.subarray(0,4).toString('ascii') === 'RIFF' && bytes.subarray(8,12).toString('ascii') === 'WEBP'; }
export async function readValidatedSourceResponse(response: Response): Promise<DownloadedSource> { const declared = Number(response.headers.get('content-length') || 0); if (declared > MAX_BYTES) throw new Error('Migration source exceeds the 5 MB image policy'); const type = (response.headers.get('content-type') || '').split(';', 1)[0].trim().toLowerCase(); if (!ALLOWED_TYPES.has(type)) throw new Error('Migration source content type is not an allowed image'); if (!response.body) throw new Error('Migration source body was empty'); const reader = response.body.getReader(); const chunks: Buffer[] = []; let total = 0; while (true) { const part = await reader.read(); if (part.done) break; total += part.value.byteLength; if (total > MAX_BYTES) { await reader.cancel(); throw new Error('Migration source exceeds the 5 MB image policy'); } chunks.push(Buffer.from(part.value)); } const bytes = Buffer.concat(chunks, total); if (!signatureMatches(type, bytes)) throw new Error('Migration source bytes do not match the declared image type'); return { bytes, contentType: type, sha256: createHash('sha256').update(bytes).digest('hex') }; }
function requestPinned(url: URL, address: string, family: 4 | 6): Promise<Response> { return new Promise((resolve, reject) => { const transport = url.protocol === 'https:' ? https : http; const request = transport.request({ protocol: url.protocol, hostname: url.hostname.replace(/^\[|\]$/g, ''), port: url.port || undefined, path: `${url.pathname}${url.search}`, servername: url.hostname.replace(/^\[|\]$/g, ''), lookup: (_host, options, callback) => options.all ? callback(null, [{ address, family }]) : callback(null, address, family), headers: { Host: url.host } }, (res) => { const headers = new Headers(); for (const [key, value] of Object.entries(res.headers)) if (value) headers.set(key, Array.isArray(value) ? value.join(', ') : value); let cancelled = false; const body = new ReadableStream<Uint8Array>({ start(controller) { res.on('data', (chunk) => { if (!cancelled) controller.enqueue(new Uint8Array(chunk)); }); res.on('end', () => { if (!cancelled) controller.close(); }); res.on('error', (error) => { if (!cancelled) controller.error(error); }); }, cancel() { cancelled = true; res.destroy(); } }); resolve(new Response(body, { status: res.statusCode || 0, headers })); }); const deadline = setTimeout(() => request.destroy(new Error('Migration source request timed out')), 10_000); request.on('close', () => clearTimeout(deadline)); request.on('error', reject); request.end(); }); }
export async function downloadTrustedSource(sourceUrl: string, allowedPrefixes: readonly string[]): Promise<DownloadedSource> { const url = new URL(sourceUrl); if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password) throw new Error('Migration source must use a credential-free HTTP(S) URL'); if (!trustedPrefix(url, allowedPrefixes)) throw new Error('Migration source is outside the configured legacy allowlist'); const pinned = await resolvePinned(url.hostname); const response = await requestPinned(url, pinned.address, pinned.family); if (response.status >= 300 && response.status < 400) throw new Error('Migration source redirects are not allowed'); if (!response.ok) throw new Error(`Migration source returned HTTP ${response.status}`); return readValidatedSourceResponse(response); }
export async function copyAndVerifyObject(client: S3Client, bucket: string, entry: MigrationManifestEntry, source: DownloadedSource): Promise<MigrationManifestEntry> { if (!entry.targetObjectKey) throw new Error('Migration entry has no target object key'); await client.send(new PutObjectCommand({ Bucket: bucket, Key: entry.targetObjectKey, Body: source.bytes, ContentType: source.contentType })); const head = await client.send(new HeadObjectCommand({ Bucket: bucket, Key: entry.targetObjectKey })); if (head.ContentLength !== source.bytes.length || head.ContentType !== source.contentType) throw new Error('Target object metadata verification failed'); const result = await client.send(new GetObjectCommand({ Bucket: bucket, Key: entry.targetObjectKey })); if (!result.Body) throw new Error('Target object readback was empty'); const readback = Buffer.from(await result.Body.transformToByteArray()); if (createHash('sha256').update(readback).digest('hex') !== source.sha256) throw new Error('Target object content verification failed'); return { ...entry, migrationState: 'verified' }; }
export function rewriteFixture(records: Array<{ recordId: string; imageUrls: string[] }>, manifest: MigrationManifestEntry[]): Array<{ recordId: string; imageUrls: string[] }> { const bySource = new Map<string, string>(); for (const entry of manifest.filter((item) => item.migrationState === 'verified' && item.targetPublicUrl)) { const key = `${entry.recordId}\n${entry.originalUrl}`; if (bySource.has(key)) throw new Error('Migration manifest source identity collision'); bySource.set(key, entry.targetPublicUrl!); } return records.map((record) => ({ ...record, imageUrls: record.imageUrls.map((url) => bySource.get(`${record.recordId.trim()}\n${url}`) || url) })); }
export function rollbackFixture(records: Array<{ recordId: string; imageUrls: string[] }>, manifest: MigrationManifestEntry[]): Array<{ recordId: string; imageUrls: string[] }> { const byTarget = new Map<string, string>(); for (const entry of manifest.filter((item) => item.migrationState === 'verified' && item.targetPublicUrl)) { const key = `${entry.recordId}\n${entry.targetPublicUrl}`; if (byTarget.has(key)) throw new Error('Migration manifest target identity collision'); byTarget.set(key, entry.originalUrl); } return records.map((record) => ({ ...record, imageUrls: record.imageUrls.map((url) => byTarget.get(`${record.recordId.trim()}\n${url}`) || url) })); }
